services:
  mc:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    environment:
      EULA: "true"
      TYPE: "FABRIC"
      VERSION: "1.21.6"
      PLUGINS: |
        https://cdn.modrinth.com/data/P7dR8mSH/versions/N3z6cNQv/fabric-api-0.127.1%2B1.21.6.jar
        https://download.geysermc.org/v2/projects/geyserpreview/versions/pr.5603/builds/latest/downloads/fabric
        https://cdn.modrinth.com/data/bWrNNfkb/versions/dNRdr9Ra/Floodgate-Fabric-2.2.4-b44.jar
        https://cdn.modrinth.com/data/cKrS5WCg/versions/5pD5TgTl/hurricane-fabric-2.1.0%2Bbuild.183.jar
      SEED: "2786386421968123439"
      SPAWN_PROTECTION: 0
      ENFORCE_SECURE_PROFILE: "false"
      RESOURCE_PACK: http://localhost/resourcepacks/ExpandedItems-resourcepack.zip
      RESOURCE_PACK_ID: daf5c51f-1d2f-3d92-b413-3f4335aa2070
      RESOURCE_PACK_SHA1: SHASUM
      RCON_CMDS_STARTUP: |-
        setworldspawn 2 123 0
        gamerule spawnRadius 0
        scoreboard objectives add TotalDamage minecraft.custom:minecraft.damage_dealt "Total Damage"
        scoreboard objectives setdisplay sidebar TotalDamage
        scoreboard objectives setdisplay sidebar expanded_items.current_repair_cost
        setblock 0 123 0 minecraft:chest[facing=east]{Items:[{Slot:0,id:copper_block,count:64},{Slot:1,id:iron_ingot,count:64},{Slot:2,id:stick,count:64},{Slot:3,id:stick,count:64},{Slot:4,id:smithing_table},{Slot:5,id:crafting_table},{Slot:6,id:amethyst_block,count:64},{Slot:7,id:diamond_block,count:64},{Slot:8,id:glow_item_frame,count:64}]} destroy
        difficulty peaceful
      RCON_CMDS_ON_CONNECT: |-
        recipe give @a *
      MODE: "survival" 
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - ./output:/output
      - ./output/server:/data
    restart: unless-stopped
    network_mode: host
  dl:
    image: nginx
    volumes:
      - ./output/:/usr/share/nginx/html
    ports:
      - "80:80"
    network_mode: host
