name: Package the extension and release tags

on: [push]

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      
      - name: Package
        run: make package

      - name: Save Artifacts on Build
        uses: actions/upload-artifact@v4
        with:
          name: ExpandedItems-SNAPSHOT.zip
          path: output

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/datapacks/ExpandedItems-datapack.zip
            output/resourcepacks/ExpandedItems-resourcepack.zip
            output/mcpacks/ExpandedItems-resourcepack.mcpack
            output/mcpacks/ExpandedItems-geyser_mappings.json
