name: Validate Commits

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      
      - name: Package
        run: make package

      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ExpandedItems-SNAPSHOT.zip
          path: output
